spring:
  application:
    name: PredictingHousePrice

  datasource:
    url: jdbc:mysql://localhost:3306/housepredict
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
