spring:
  application:
    name: PredictingHousePrice

  datasource:
    url: ${URL_DB}
    username: ${USERNAMEE}
    password: ${PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
    cookie:
      http-only: true
      same-site: strict

  resources:
    static-locations: file:./uploads/

    servlet:
      multipart:
        enabled: true

server:
  address: 0.0.0.0
  port: 8080
