USE [master]
GO
/****** Object:  Database [PredictHouse]    Script Date: 4/3/2025 9:41:42 PM ******/
CREATE DATABASE [PredictHouse]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PredictHouse', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\PredictHouse.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PredictHouse_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\PredictHouse_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [PredictHouse] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PredictHouse].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [PredictHouse] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [PredictHouse] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [PredictHouse] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [PredictHouse] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [PredictHouse] SET ARITHABORT OFF 
GO
ALTER DATABASE [PredictHouse] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [PredictHouse] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [PredictHouse] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [PredictHouse] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PredictHouse] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [PredictHouse] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [PredictHouse] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PredictHouse] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [PredictHouse] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PredictHouse] SET  DISABLE_BROKER 
GO
ALTER DATABASE [PredictHouse] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PredictHouse] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PredictHouse] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [PredictHouse] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [PredictHouse] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PredictHouse] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [PredictHouse] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [PredictHouse] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [PredictHouse] SET  MULTI_USER 
GO
ALTER DATABASE [PredictHouse] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [PredictHouse] SET DB_CHAINING OFF 
GO
ALTER DATABASE [PredictHouse] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [PredictHouse] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [PredictHouse] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [PredictHouse] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [PredictHouse] SET QUERY_STORE = ON
GO
ALTER DATABASE [PredictHouse] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [PredictHouse]
GO
/****** Object:  Table [dbo].[Account]    Script Date: 4/3/2025 9:41:43 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Account](
	[UserID] [varchar](50) NOT NULL,
	[Name] [varchar](100) NOT NULL,
	[Email] [varchar](100) NOT NULL,
	[Password] [varchar](100) NOT NULL,
	[Phone] [varchar](20) NULL,
	[Role] [varchar](50) NOT NULL,
	[State] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Admin]    Script Date: 4/3/2025 9:41:43 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Admin](
	[UserID] [varchar](50) NOT NULL,
	[Name] [varchar](100) NOT NULL,
	[Email] [varchar](100) NOT NULL,
	[Password] [varchar](100) NOT NULL,
	[Phone] [varchar](20) NULL,
	[Role] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Feedback]    Script Date: 4/3/2025 9:41:43 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Feedback](
	[FeedbackID] [varchar](50) NOT NULL,
	[UserID] [varchar](50) NULL,
	[Date] [date] NULL,
	[Message] [text] NULL,
	[Title] [varchar](200) NULL,
PRIMARY KEY CLUSTERED 
(
	[FeedbackID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PredictedHouse]    Script Date: 4/3/2025 9:41:43 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PredictedHouse](
	[PredictionID] [varchar](50) NOT NULL,
	[HouseType] [varchar](50) NULL,
	[Area] [decimal](10, 2) NULL,
	[Address] [varchar](200) NULL,
	[Floors] [int] NULL,
	[Bedrooms] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[PredictionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Prediction]    Script Date: 4/3/2025 9:41:43 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Prediction](
	[PredictionID] [varchar](50) NOT NULL,
	[UserID] [varchar](50) NULL,
	[Date] [date] NULL,
	[PredictedPrice] [decimal](15, 2) NULL,
	[ConfidenceScore] [float] NULL,
PRIMARY KEY CLUSTERED 
(
	[PredictionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SellingHouse]    Script Date: 4/3/2025 9:41:43 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SellingHouse](
	[Title] [varchar](200) NOT NULL,
	[UserID] [varchar](50) NULL,
	[Area] [decimal](10, 2) NULL,
	[Address] [varchar](200) NULL,
	[Floors] [int] NULL,
	[Bedrooms] [int] NULL,
	[Bathrooms] [int] NULL,
	[LegalStatus] [varchar](50) NULL,
	[Price] [decimal](15, 2) NULL,
	[Description] [text] NULL,
	[Image] [varchar](200) NULL,
	[State] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[Title] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 4/3/2025 9:41:43 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[UserID] [varchar](50) NOT NULL,
	[Name] [varchar](100) NOT NULL,
	[Email] [varchar](100) NOT NULL,
	[Password] [varchar](100) NOT NULL,
	[Role] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Feedback]  WITH CHECK ADD FOREIGN KEY([UserID])
REFERENCES [dbo].[Account] ([UserID])
GO
ALTER TABLE [dbo].[PredictedHouse]  WITH CHECK ADD FOREIGN KEY([PredictionID])
REFERENCES [dbo].[Prediction] ([PredictionID])
GO
ALTER TABLE [dbo].[Prediction]  WITH CHECK ADD FOREIGN KEY([UserID])
REFERENCES [dbo].[Account] ([UserID])
GO
ALTER TABLE [dbo].[SellingHouse]  WITH CHECK ADD FOREIGN KEY([UserID])
REFERENCES [dbo].[Account] ([UserID])
GO
USE [master]
GO
ALTER DATABASE [PredictHouse] SET  READ_WRITE 
GO
